version: '3.8'
services:
  go-app:
    container_name: basic-introduction-to-grpc-in-go
    build: .
    volumes:
      - ../:/app:cached
    ports:
      - 8080:8080
    command: /bin/sh -c "while sleep 1000; do :; done"
    